name: file operations

on: workflow_dispatch

jobs:
  files:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
      uses: actions/checkout@v5
    - name: display the content of a file
      run: cat devops.sh
    - name: execute permission
      run: chmod u+x devops.sh
    - name: execute script
      run: sh devops.sh
